on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: verifica o reposit처rio Git
        uses: actions/checkout@v2

      - name: Instala o node com a vers찾o
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: instalando dependencias
        run: npm install

      - name: executando o lint para verificar se a erros
        run: npx eslint .
  Testes_unitarios:
    runs-on: ubunto-latest
    needs: [eslint]
    steps:
      - name: verifica o reposit처rio Git
        uses: actions/checkout@v2

      - name: Instala o node com a vers찾o
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: instalando dependencias
        run: npm install

      - name: executando os testes
        run: npm run test